name: Check Certificate Expiry

on:
  schedule:
    - cron: '*/1 * * * *'  # Esegui ogni minuto
  push:
    branches:
      - IDP-2515-update-thumbprint
jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Run script
        run: |
          # Script Bash inizia qui
          vault_name="cstar-d-idpay-kv"
          certificate_name="cstar-d-weu-idpay-idpay-merchants-jwt-signing-cert"

          certificate_info=$(az keyvault certificate show --name "$certificate_name" --vault-name "$vault_name")
          expiration_date=$(echo "$certificate_info" | awk -F'"' '/"expires":/{print $4}')
          days_until_expiration=$(( ($(date -d "$expiration_date" +%s) - $(date +%s)) / 86400 ))

          threshold_days=365

          if [ $days_until_expiration -lt $threshold_days ]; then
              echo "$(date): Attenzione: Il certificato $certificate_name sta per scadere tra $days_until_expiration giorni."
          else
              echo "$(date): Il certificato $certificate_name non scadrà entro $threshold_days giorni. Nessuna azione necessaria."
          fi

          echo "Data di scadenza del certificato: $expiration_date"

          read -p "Premi INVIO per continuare..."
          # Script Bash termina qui
